<h1>Tables des matières<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Réduction-de-dimensions-et-Analyse-de-composantes-principales-(ACP)" data-toc-modified-id="Réduction-de-dimensions-et-Analyse-de-composantes-principales-(ACP)-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Réduction de dimensions et Analyse de composantes principales (ACP)</a></span><ul class="toc-item"><li><span><a href="#Chargement-du-Iris-Dataset-(i.e.-scikit-learn-iris)" data-toc-modified-id="Chargement-du-Iris-Dataset-(i.e.-scikit-learn-iris)-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Chargement du Iris Dataset (i.e. scikit-learn iris)</a></span></li></ul></li></ul></div>


# Réduction de dimensions et Analyse de composantes principales (ACP)

In [4]:
# Imports de base
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl
import pandas as pd
#from bokeh.plotting import figure,show,output_notebook

#import pour la classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
 
# import pour PCA
from sklearn.decomposition import PCA


## Chargement du Iris Dataset (i.e. scikit-learn iris)  


In [4]:
#Import du dataset Iris
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
#Afficher le dataset
print (iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
#Features et target
X = iris.data
y = iris.target
noms_target = iris.target_names

* Algorithme PCA prend un argument `n_components` qui spécifie le nombre de composantes principales que l'on va garder.  Dans le cas du dataset Iris on a seulement 4 features. On commence avec 2 features. 

In [7]:
# creer le modele et effectuer un fit du data
pca = PCA(n_components=2)
X_resultat = pca.fit(X).transform(X)

In [8]:
X_resultat

array([[-2.68420713,  0.32660731],
       [-2.71539062, -0.16955685],
       [-2.88981954, -0.13734561],
       [-2.7464372 , -0.31112432],
       [-2.72859298,  0.33392456],
       [-2.27989736,  0.74778271],
       [-2.82089068, -0.08210451],
       [-2.62648199,  0.17040535],
       [-2.88795857, -0.57079803],
       [-2.67384469, -0.1066917 ],
       [-2.50652679,  0.65193501],
       [-2.61314272,  0.02152063],
       [-2.78743398, -0.22774019],
       [-3.22520045, -0.50327991],
       [-2.64354322,  1.1861949 ],
       [-2.38386932,  1.34475434],
       [-2.6225262 ,  0.81808967],
       [-2.64832273,  0.31913667],
       [-2.19907796,  0.87924409],
       [-2.58734619,  0.52047364],
       [-2.3105317 ,  0.39786782],
       [-2.54323491,  0.44003175],
       [-3.21585769,  0.14161557],
       [-2.30312854,  0.10552268],
       [-2.35617109, -0.03120959],
       [-2.50791723, -0.13905634],
       [-2.469056  ,  0.13788731],
       [-2.56239095,  0.37468456],
       [-2.63982127,

# On cherche maintenant le pourcentage de variance pris en charge par les 2 composantes PCA. On utilise l'attribut `explained_variance_ratio_` :

In [1]:
# Pourcentage de variance explained  :
 

* Conclusion:


In [10]:
echelle_couleur = {0:'red',1:'blue',2:'orange'}

couleurs = list()

for valeur in y:
    couleur = echelle_couleur[valeur]
    couleurs.append(couleur)


In [32]:
#Plot comme scatter
p_fig = figure(title="PCA dans le Iris Dataset",tools='')

 

# On utilise maintenant une technique simple pour evaluer si le choix de n=2 est adéquat.On refait la même procédure mais avec toutes les composantes:

In [12]:
# créer le modele mais sans spécifier n_components:
 

In [13]:
#Afficher les variances expliqués

In [4]:
variance_explique = pca.explained_variance_ratio_
 

In [15]:
#Afficher les composantes PCA
print (pca.components_)

In [17]:
comp_id = [1, 2, 3, 4]             # id du composant
p_pca = figure(title="Composantes principales",tools='',
           x_axis_label="Principal Component",
          y_axis_label='Variance Expliquée')
p_pca.line(comp_id,variance_explique,color='red')
show(p_pca)


Conclusion:


# On evalue maintenant si la vitesse de traitement est améliorée en prenant moins de feature ou plus de features

In [18]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.2, random_state=42)

Pour simplifier, on utilise la fonction `%%timeit` pour effectuer une classification selon la sélection de features

In [19]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_train, y_train)

200 µs ± 2.62 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [20]:
modele = KNeighborsClassifier(2)
modele.fit(X_train, y_train)
print (classification_report(y_test,modele.predict(X_test)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [21]:
X_r_train, X_r_test, y_r_train, y_r_test = train_test_split(X_resultat,y, test_size=0.2, random_state=42)

In [22]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)

208 µs ± 3.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


Conclusion:

In [23]:
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)
print (classification_report(y_r_test,modele.predict(X_r_test)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [24]:
# refaire maintenant avec 2 composantes principales
# creer le modele et effectuer un fit du data
 


In [25]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train2, y_r_train2)

206 µs ± 4.42 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
modele2 = KNeighborsClassifier(2)
modele2.fit(X_r_train2, y_r_train2)
print (classification_report(y_r_test2,modele2.predict(X_r_test2)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



# Solutionnaires

In [4]:
# Imports de base
import numpy as np
import matplotlib.pyplot as plt
import pylab as pl
import pandas as pd
#from bokeh.plotting import figure,show,output_notebook

#import pour la classification
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
 
# import pour PCA
from sklearn.decomposition import PCA


## Chargement du Iris Dataset (i.e. scikit-learn iris)  


In [4]:
#Import du dataset Iris
from sklearn.datasets import load_iris
iris = load_iris()

In [5]:
#Afficher le dataset
print (iris)

{'data': array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
     

In [6]:
#Features et target
X = iris.data
y = iris.target
noms_target = iris.target_names

In [7]:
# creer le modele et effectuer un fit du data
pca = PCA(n_components=2)
X_resultat = pca.fit(X).transform(X)

In [8]:
X_resultat

array([[-2.68420713,  0.32660731],
       [-2.71539062, -0.16955685],
       [-2.88981954, -0.13734561],
       [-2.7464372 , -0.31112432],
       [-2.72859298,  0.33392456],
       [-2.27989736,  0.74778271],
       [-2.82089068, -0.08210451],
       [-2.62648199,  0.17040535],
       [-2.88795857, -0.57079803],
       [-2.67384469, -0.1066917 ],
       [-2.50652679,  0.65193501],
       [-2.61314272,  0.02152063],
       [-2.78743398, -0.22774019],
       [-3.22520045, -0.50327991],
       [-2.64354322,  1.1861949 ],
       [-2.38386932,  1.34475434],
       [-2.6225262 ,  0.81808967],
       [-2.64832273,  0.31913667],
       [-2.19907796,  0.87924409],
       [-2.58734619,  0.52047364],
       [-2.3105317 ,  0.39786782],
       [-2.54323491,  0.44003175],
       [-3.21585769,  0.14161557],
       [-2.30312854,  0.10552268],
       [-2.35617109, -0.03120959],
       [-2.50791723, -0.13905634],
       [-2.469056  ,  0.13788731],
       [-2.56239095,  0.37468456],
       [-2.63982127,

# On cherche maintenant le pourcentage de variance pris en charge par les 2 composantes PCA. On utilise l'attribut `explained_variance_ratio_` :

In [9]:
# Pourcentage de variance explained  :
print ("Composant 1: " + str(pca.explained_variance_ratio_[0]))
print ("Composant 2: " + str(pca.explained_variance_ratio_[1]))

Composant 1: 0.9246162071742684
Composant 2: 0.053015567850534955


* On voit que les 2 composantes prennent en charge presque la totalité de la variance.  On procède maintenant au tracé des point du dataset dans le système de coordonnées ou bases PCA.  Les labels utilisés sont ceux des targets:

In [10]:
echelle_couleur = {0:'red',1:'blue',2:'orange'}

couleurs = list()

for valeur in y:
    couleur = echelle_couleur[valeur]
    couleurs.append(couleur)


In [32]:
#Plot comme scatter
p_fig = figure(title="PCA dans le Iris Dataset",tools='')

x_values =  X_resultat[:,0]
y_values =  X_resultat[:,1]
p_fig.circle(x = x_values,y=y_values,size = 5,color=couleurs)

show(p_fig)

# On utilise maintenant une technique simple pour evaluer si le choix de n=2 est adéquat.On refait la même procédure mais avec toutes les composantes:

In [12]:
# créer le modele mais sans spécifier n_components:
pca = PCA()
X_resultat = pca.fit(X).transform(X)

In [13]:
#Afficher les variances expliqués

In [14]:
variance_explique = pca.explained_variance_ratio_
print (variance_explique)

[0.92461621 0.05301557 0.01718514 0.00518309]


In [15]:
#Afficher les composantes PCA
print (pca.components_)

In [17]:
comp_id = [1, 2, 3, 4]             # id du composant
p_pca = figure(title="Composantes principales",tools='',
           x_axis_label="Principal Component",
          y_axis_label='Variance Expliquée')
p_pca.line(comp_id,variance_explique,color='red')
show(p_pca)


On voit qu’avec 2 composantes, on est capable de capturer l’essentiel des features.

# On evalue maintenant si la vitesse de traitement est améliorée en prenant moins de feature ou plus de features

In [20]:
modele = KNeighborsClassifier(2)
modele.fit(X_train, y_train)
print (classification_report(y_test,modele.predict(X_test)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [21]:
X_r_train, X_r_test, y_r_train, y_r_test = train_test_split(X_resultat,y, test_size=0.2, random_state=42)

In [22]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)

208 µs ± 3.23 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [23]:
modele = KNeighborsClassifier(2)
modele.fit(X_r_train, y_r_train)
print (classification_report(y_r_test,modele.predict(X_r_test)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30



In [24]:
# refaire maintenant avec 2 composantes principales
# creer le modele et effectuer un fit du data
pca_2 = PCA(n_components=2)
X_resultat_2 = pca.fit(X).transform(X)
X_r_train2, X_r_test2, y_r_train2, y_r_test2 = train_test_split(X_resultat_2,y, test_size=0.2, random_state=42)


In [25]:
%%timeit 
modele = KNeighborsClassifier(2)
modele.fit(X_r_train2, y_r_train2)

206 µs ± 4.42 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [26]:
modele2 = KNeighborsClassifier(2)
modele2.fit(X_r_train2, y_r_train2)
print (classification_report(y_r_test2,modele2.predict(X_r_test2)) )

             precision    recall  f1-score   support

          0       1.00      1.00      1.00        10
          1       1.00      1.00      1.00         9
          2       1.00      1.00      1.00        11

avg / total       1.00      1.00      1.00        30

